### ISSUE TITLE
[ex] Ping timeout crashes the server handler.

### ISSUE THREAD

**Issue by jhgg** [discordapp/loqui#19]
When a pong is not received, the following code is ran:

```elixir
  defp ping(%{pong_received: false}=state),
    do: goaway(state, :ping_timeout)
```

goaway always returns `:ok`.

This breaks in this chain:

```elixir
      :send_ping ->
        state
          |> ping
          |> handler_loop(so_far)
```

as we are passing `[:ok, <<>>]` to `handler_loop`.

Rough crash looks like:

```
{:function_clause,
 [{Loqui.RanchProtocol, :handler_loop, [:ok, ""],
   [file: 'ex/loqui/lib/loqui/ranch_protocol.ex', line: 70]},
  {Loqui.Server.Http, :loop, 1,
   [file: 'ex/loqui/lib/loqui/server.ex', line: 47]}]}
```

**Comment by scohen** [comment]
So, I think crashing the client is expected for a pong failing, but the error isn't right, correct?

**Comment by scohen** [comment]
Also, this is a server problem, correct?

**Comment by jhgg** [comment]
Duh, correct. The traceback is in server.ex too. My bad
