### ISSUE TITLE
Loqui.Client.close/1 results in unknown request on server

### ISSUE THREAD

**Issue by tsutsu** [discordapp/loqui#27]
On Elixir client:
```
iex(1)> {:ok, client} = Loqui.Client.start_link("localhost", 8080, "/rpc", loqui_opts: [codecs: [Loqui.Protocol.Codecs.Erlpack]])
{:ok, #PID<0.237.0>}
iex(2)> client |> Loqui.Client.close
:ok
```

On Elixir server, logs:
```
12:47:34.167 [info]  unknown request. request={:go_away, 0, 0, "Closing"}
12:47:34.167 [info]  [loqui] tcp_closed. socket_pid=#Port<0.11>
```

Apparently, there is no `handle_request({:go_away, _flags, seq, reason}, state)` clause in `ranch_protocol.ex`. (I'd PR, but I'm not sure what that handler should do, semantically.)

**Comment by scohen** [comment]
Looks like this is a client bug; The client shouldn't send a goaway packet when it closes.
